### ISSUE TITLE
"Calc" on a property is not working correctly

### ISSUE THREAD

**Issue by AitorRodriguez990** [gulp-community/gulp-less#297]
Hi there,
I'm using gulp-less on a new proyect and I'm having problems using "calc".

My **less** file has:
```less
width: ~"calc(100% - 720px)";
```

And the output on **css** files is:
```css
width: calc(-620%);
```

Instead of:
```css
width: calc(100% - 720px);
```

Thank you!

**Comment by contra** [comment]
Can you test this with the `less` command directly? If it outputs the same thing you need to open an issue on their repository, not here since we're just wrapping that library.

**Comment by AitorRodriguez990** [comment]
Thank you for the answer, @contra.

I don't understand what are you trying to tell me. I cleared my code to find the problem, but it works badly yet.

My code:
```js
return gulp.src(files, { base: "Styles" })
        .pipe(less())
        .pipe(gulp.dest(bundlesPath))
```

So, do you think is a less problem? These less files are working correctly with Visual Studio's web-compiler plugin.

**Comment by AitorRodriguez990** [comment]
Thank you again, @contra 

I did you told me. I think is a `gulp-less` problem because the output is different. For example, this `less`code:
```less
.footer-apps {
  width: ~"calc(100% - 720px)";
}
```

Output with `gulp-less`:
```css
.footer .footer-apps {
    width: calc(-620%);
}
```

Output with `less` directly (command line tool): 
```css
.footer .footer-apps {
  width: calc(100% - 720px);
}
```

My `node` version is 8.9.1 and `less` version is 3.8.0.
