### ISSUE TITLE
-webkit-box-orient: vertical;  not transfer to css?

### ISSUE THREAD

**Issue by wxungang** [gulp-community/gulp-less#300]
```less
.ellipsis(@n) when (@n>1) {
  word-break: break-all;
  overflow: hidden;
  text-overflow: ellipsis;
  //white-space: nowrap;

  -webkit-line-clamp: @n;
  -webkit-box-orient: vertical; //will not export to css!!
  display: -webkit-box;
}

.ellipsis(@n) when (default()) {
  //word-break: break-all;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

//exports your module
.up-ellipsis(@n:1) {
  .ellipsis(@n) !important;
}
```
