### ISSUE TITLE
Compiling @font-face with format('woff2') - Unrecognized input

### ISSUE THREAD

**Issue by danimalweb** [gulp-community/gulp-less#90]
Unable to compile less when Including format('woff2') in @font-face.

This is my @font-face:

``` css
@font-face {
    font-family: 'PT Sans';
    src: url('../assets/fonts/PTSans-Regular-webfont.woff2') format('woff2');
         url('../assets/fonts/PTSans-Regular-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;
}
```

Error received on compile:

Unrecognised input in file fonts.less line no. 4
